environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

  matrix:

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
build: off

before_test:
  - python -u setup.py build_ext --inplace

test_script:
  - python -u setup.py unittests

after_test:
  - python -u setup.py bdist_wheel

artifacts:
  - path: dist
    name: td3a_cpp
